### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by callebtc** [trentrand/capacitor-nfc#1]
Hi there, I found this cool plugin that I would like to use for my FOSS project but it doesn't have a license. Could you add one?

**Comment by prusnak** [comment]
may I suggest using MIT License which is used by Capacitor itself?

https://github.com/ionic-team/capacitor/blob/main/LICENSE

**Comment by trentrand** [comment]
Yes, absolutely! I pushed commit [285a399](https://github.com/trentrand/capacitor-nfc/commit/285a39983e8d15abacbe88801af8b15fdf299d63) with a MIT License.

This plugin is a free alternative to the capawesome/capacitor-nfc plugin, but it needs some effort to reach the same stability and feature set. The iOS version is untested, so I foresee issues there, but web and Android are working well in my project. I plan to get to iOS in the next few days, but I would be happy to see contributions too!

**Comment by trentrand** [comment]
@callebtc / @prusnak , did you use the plugin on iOS? Any patches you can contribute back to get it working?

**Comment by prusnak** [comment]
> @callebtc / @prusnak , did you use the plugin on iOS? Any patches you can contribute back to get it working?

Not yet ... but we will surely contribute if we have some issues that need fixing

**Comment by trentrand** [comment]
I pushed some changes in #2 that you'll find useful:


**0.2.0 improves the data output so that it's always returned as a Dataview** 

>   Preprocess nfcTagRead event so that data payload is always a DataView
>   The last release had an inconsistent API, where Web would return a
>   DataView with 8-bit values, while Android would return an Array<number>.
> 
>   Cross-platform codebases would have to handle this in their
>   implementation by checking the type at runtime and converting if
>   necessary.
> 
>   Now we always return a DataView, and so the consumer is setup for
>   success with the 8-bit payload that can be converted to utf-8 or
>   whatever their use case requires.

**0.3.0 fixes NFC scanning on iOS**

> I finally have an Apple Developer account, so I tested the implementation
> and got it to a baseline _working_ state. I added some instructions to the
> README.md to help with setting up Xcode.
